config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  get  '/help',    to: 'landing_pages#help'
  get  '/about',   to: 'landing_pages#about'
  get  '/contact', to: 'landing_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'session#new'
  post  '/login',   to: 'session#create'
  delete  '/logout',  to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end

  resources :microposts do
    resource :like, only: [:show, :create, :destroy]
    resource :reply, only: [:create, :destroy]
  end

  resources :forgot_password, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :tags, only: [:show, :show_microposts, :show_replies]
  resources :relationships, only: [:create, :destroy]

  root 'landing_pages#home'
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  def home
    if logged_in?
      @user = current_user
      @micropost  =  @user.microposts.build
      @feed_items =  @user.feed.paginate(page: params[:page], :per_page => 4)
    else
      @feed_items =  Micropost.order('created_at').paginate(page: params[:page], :per_page => 7)
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p class="p-center">
  This is the 'about' page for the <a href="https://github.com/R1cro/SocialNetwork/">my web-application.</a>
</p>

app/views/landing_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p class="p-center">
  This is the "contact" page for the <a href="https://github.com/R1cro/SocialNetwork/">my web-application.</a>
</p>

app/views/landing_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p class="p-center">
  This is the "help" page for the <a href="https://github.com/R1cro/SocialNetwork/">my web-application.</a>
</p>

app/views/landing_pages/home.html.erb
<% provide(:title, 'Feed') %>
<% if logged_in?  %>
  <div class="row">
    <aside class="col-md-5">
      <section class="user-info-feed">
        <%= render 'shared/about_user' %>
      </section>
      <% if logged_in? && @user.id == @current_user.id %>
        <section class="panel panel-default main-panel">
          <div class="panel-body">
            <%= render 'shared/micropost_form' %>
          </div>
        </section>
      <% end %>
      <section class="panel panel-default tag-cloud-panel">
        <div class="panel-body">
          <% if @micropost&.tag_counts.empty? %>
            <div class="empty-zone">
              <h1>Sorry</h1>
              <h4>No #tags :(</h4>
            </div>
          <% else %>
            <ol>
              <h4>Popular tags:</h4>
              <% @micropost.tag_counts.sort_by(&:count).last(8).each do |tag| %>
                <li><%= link_to '#' + tag.name, tag_path(tag.id) %></li>
              <% end %>
            </ol>
          <% end %>
        </div>
      </section>
    </aside>
      <div class="col-md-7">
        <% if @feed_items.any? %>
          <%= render 'microposts/feed' %>
        <% else %>
          <div class="empty-zone">
            <h1>Black words </h1>
            <h4>on this perfect white background.</h4>
          </div>
        <% end %>
      </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-7 col-md-offset-1 feed-for-guest">
      <%= render 'microposts/feed' %>
    </div>
  </div>
  <div class="center jumbotron">
    <span class="main-title">Social Network by R1cro</span>
    <h2>
      This is the home page for the <a href="https://github.com/R1cro/SocialNetwork/">my web-application.</a>
      If you already registered, please, <a href="/login">log in</a>.
      If you not, so, it is a time to sign up!
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Log in", login_path, class: "btn btn-lg" %>
  </div>
<% end %>

app/views/landing_pages/home.js.erb
$('.microposts').append('<%= j render(@feed_items) %>');
$("div[id|='reply-to-micropost']").hide()
<% if @feed_items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@feed_items) %>');
  $('#loading').hide();
<% else %>
  $('.pagination').remove();
  $('#loading').remove();
<% end %>