config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  get  '/help',    to: 'landing_pages#help'
  get  '/about',   to: 'landing_pages#about'
  get  '/contact', to: 'landing_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'session#new'
  post  '/login',   to: 'session#create'
  delete  '/logout',  to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end

  resources :microposts do
    resource :like, only: [:show, :create, :destroy]
    resource :reply, only: [:create, :destroy]
  end

  resources :forgot_password, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :tags, only: [:show, :show_microposts, :show_replies]
  resources :relationships, only: [:create, :destroy]

  root 'landing_pages#home'
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        if params[:session][:remember_me] == '1'
          remember(user)
        else
          forget(user)
        end
        redirect_back_or root_url
      else
        flash[:danger] = "Your account not activated. Check your email for the activation link."
        redirect_to root_url
      end
    else
      flash.now[:danger]  = 'Invalid email/password combination! Please, try again.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Access to this page allowed only for users. Sign in to access this page."
      redirect_to login_url
    end
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/views/session/new.html.erb
<% provide(:title, 'Sign In') %>
<h1>Log in</h1>
<div id="show_row" class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <span class="forgot-password"><%= link_to " Forgot password?", new_forgot_password_path %></span>
      <%= f.password_field :password, class: 'form-control' %>


      <%= f.label :remember_me, class: "checkbox inline" do %>
          <%= f.check_box :remember_me %>
          <p class="remember-me"> Remember me </p>
      <% end %>

      <%= f.submit 'Log in', class: 'btn btn-primary' %>
    <% end %>

    <p id="new-user">or <%= link_to 'Sign up now!', signup_path %></p>
  </div>
</div>