config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  get  '/help',    to: 'landing_pages#help'
  get  '/about',   to: 'landing_pages#about'
  get  '/contact', to: 'landing_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'session#new'
  post  '/login',   to: 'session#create'
  delete  '/logout',  to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end

  resources :microposts do
    resource :like, only: [:show, :create, :destroy]
    resource :reply, only: [:create, :destroy]
  end

  resources :forgot_password, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :tags, only: [:show, :show_microposts, :show_replies]
  resources :relationships, only: [:create, :destroy]

  root 'landing_pages#home'
end

app/views/shared/_about_user.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="user-details">
      <%= avatar_for @user, 100 %>
      <h1>
        <%= @user.user_profile.first_name %>
        <%= @user.user_profile.second_name %>
      </h1>
      <p>
        <%= @user.email %>
      <br>
        <% if @user.user_profile&.birthday %>
          <%= @user.user_profile.age(@user.user_profile.birthday) %> years old.
        <% end %>
        <%= @user&.user_profile&.city %>
      </p>
    </div>
  </div>
  <% if logged_in? %>
    <%= render 'users/user_follow_form' %>
  <% end %>
</div>

app/views/shared/_birthday_field.html.erb
<div class='input-group birthday-field date datepicker'>
  <%= object.text_field :birthday, class: 'form-control' %>
  <span class="input-group-addon">
    <span class="fa fa-calendar"></span>
  </span>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<div class="micropost-form">
  <%= form_for(@micropost, html: { multipart: true, class: 'dropzone', id: 'micropost-dropzone' }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div id="dropzone-area" class="post-field">
      <%= f.text_area :content, placeholder: 'Compose new micropost or drop some images (max: 3)', id: 'dropzone-textarea', class: 'form-control', rows: 2 %>
      <button class='btn btn-default' id="dropzone-upload">Cloudinary</button>
    </div>
    <!--<span class="image">-->
      <!--<%# f.file_field(:image) %>-->
    <!--</span>-->
    <%= f.submit 'Post', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shared/_relationship.html.erb
<% @user ||= current_user %>
<a class="following-link" href="<%= following_user_path(@user) %>">
  <strong id="following">
    Following <span class="badge"><%= @user.following.count %></span>
  </strong>
</a>
<a class="followers-link" href="<%= followers_user_path(@user) %>">
  <strong id="followers">
    Followers <span class="badge"><%= @user.followers.count %></span>
  </strong>
</a>
<a class="liked-link" href="<%= liked_posts_user_path(@user) %>">
  <strong id="liked">
    Liked <span class="badge"><%= @user.likes.count %></span>
  </strong>
</a>

app/views/shared/_statistics.html.erb
<% @user ||= current_user %>
<a class="following-link" href="<%= following_user_path(@user) %>">
  <strong id="following">
    Following <span class="badge"><%= @user.following.count %></span>
  </strong>
</a>
<a class="followers-link" href="<%= followers_user_path(@user) %>">
  <strong id="followers">
    Followers <span class="badge"><%= @user.followers.count %></span>
  </strong>
</a>
<a class="liked-link" href="<%= liked_posts_user_path(@user) %>">
  <strong id="liked">
    Liked <span class="badge"><%= @user.likes.count %></span>
  </strong>
</a>