config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  get  '/help',    to: 'landing_pages#help'
  get  '/about',   to: 'landing_pages#about'
  get  '/contact', to: 'landing_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'session#new'
  post  '/login',   to: 'session#create'
  delete  '/logout',  to: 'session#destroy'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end

  resources :microposts do
    resource :like, only: [:show, :create, :destroy]
    resource :reply, only: [:create, :destroy]
  end

  resources :forgot_password, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :tags, only: [:show, :show_microposts, :show_replies]
  resources :relationships, only: [:create, :destroy]

  root 'landing_pages#home'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  include Hashtags

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :replies, dependent: :destroy
  # has_one :image, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }, allow_nil: false
  validate  :image_size

  def liked_by?(user)
     self.likes.where(user: user).present?
  end

  private
  def image_size
    if image.size > 10.megabyte
      errors.add(:image, 'Image size should be less than 10 MB!')
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user,  only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_path
    else
      redirect_to :back, flash: { danger: @micropost.errors.full_messages.join('<br><li>') }
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'Micropost deleted'
    redirect_to request.referrer
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content, :image, :id)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_feed.html.erb
<% if @feed_items.any? %>
  <h5>Last users posts</h5>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <% if logged_in? %>
    <div id="scrolling">
      <div id="loading"><img src="/ajax-loader.gif" alt="Loading..."></div>
      <%= will_paginate @feed_items %>
    </div>
  <% end %>
<% end %>

app/views/microposts/_like.html.erb
<%= form_for(:like, url: micropost_like_path(micropost.id), remote: true) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.button do %>
      <i class="fa fa-heart-o" aria-hidden="true"></i>
    <% end %>
<% end %>

app/views/microposts/_like_form.html.erb
<div id="likes-form-<%= micropost.id %>">
  <% if logged_in? %>
    <% if micropost.liked_by?(current_user) %>
      <%= render 'microposts/unlike', micropost: micropost  %>
    <% else %>
      <%= render 'microposts/like', micropost: micropost %>
    <% end %>
  <% end %>
</div>

app/views/microposts/_likes.html.erb
<% if logged_in? %>
  <div id="like-count-<%= micropost.id %>">
    <% if micropost.likes.count != 0 %>
      <span class="badge liked"><%= link_to micropost.likes.count, micropost_like_url(micropost.id) %></span>
    <% else %>
      <span class="badge"><%= micropost.likes.count %></span>
    <% end %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <li id="micropost-<%= micropost.id %>">
      <%= link_to avatar_for(micropost.user, 0), micropost.user %>
      <% if micropost.user.user_profile.first_name.nil? %>
        <h4 class="post-owner"><%= link_to micropost.user.email , micropost.user %></h4>
      <% else %>
        <h4 class="post-owner"><%= link_to micropost.user.user_profile.first_name + ' ' + micropost.user.user_profile.second_name , micropost.user %></h4>
      <% end %>
      <span class="content"><%= process_content(micropost) %></span>
      <div class="post-image"><%= image_tag micropost.image.url if micropost.image? %></div>
      <div class="like-panel row">
        <div class="like-form col-sm-2">
          <%= render 'microposts/like_form', micropost: micropost %>
          <%= render 'microposts/likes', micropost: micropost  %>
        </div>
        <div><%= render 'microposts/post_likers', micropost: micropost %> </div>
      </div >
      <span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <span class="remove-post">
        <% if current_user?(micropost.user) %>
          <%= link_to micropost, method: :delete,
                                data: { confirm: 'Remove your post?' },
                                class: 'post-delete-link' do %>
          <i class="fa fa-lg fa-trash"></i>
          <% end %>
        <% end %>
        </span>
      </span>
      <% if logged_in? %>
        <hr><button onclick="toggleReply(<%= micropost.id %>)" id="show-replies-<%= micropost.id %>" class="toggle"><i class="fa fa-reply" aria-hidden="true"></i> REPLY</button>
        <div id="reply-to-micropost-<%= micropost.id %>">
          <hr>
          <div class="replies-panel">
            <%= render 'replies/reply', micropost: micropost %>
          </div>
          <hr>
          <%= render 'replies/reply_form', micropost: micropost %>
        </div>
      <% end %>
    </li>
  </div>
</div>

app/views/microposts/_post_likers.html.erb
<% if logged_in? %>
  <div id="liker-avatars-<%= micropost.id %>">
    <% micropost.likes.last(7).reverse.each do |like| %>
      <%= link_to avatar_for(like.user, 40), like.user, id: "user-avatar-#{like.user.id}" %>
    <% end %>
  </div>
<% end %>

app/views/microposts/_unlike.html.erb
<%= form_for(:like, url: micropost_like_path(micropost.id), method: :delete, remote: true) do |f| %>
  <%= f.button do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
<% end %>